---
title: "Priors_SCex"
author: "karine Durand"
date: "24 octobre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/fastSimBac_linux/Priors_SC")
```

## Générer des paramètres (Priors) 

Ce script permet de générer des priors pour le modèle Démographique SC selon des distributions uniforme ou log-uniforme 

```{r cars}
######partie locus 
#variables locus
#-L=taille du gene
#-t=theta
#-r=rho
#-delta=taille du track recombinant
#boucle de 1000000 iterations(1000000 tirage demographique)
demo<-NULL
locus<-NULL
tbs<-NULL
#####TIRER un prior locus dans une distribution uniforme de bornes 
L<-round(runif(1368,100,2500))#bound_taille du gene[100-2500]
t<-runif(1368,0, 0.0003 )#bound_theta=[0-0.0003]bornes pour 13pauca_multiplex
r<-runif(1368,0,0.0006)##bound_rho=[0,0.0006]
delta<-round(runif(1368,10, 1000))#bound=[10-1000]
#print(L,t,r,delta)
m_locus=matrix(c(L,t,r,delta),ncol=4)
m_locus=as.data.frame(m_locus)

for (i in 1:10000){#tirage des priors demographiques
  #variables demographique modéle SC
  ##Param_demo (7) =  Ts,  N1,  N2,M12, M21, Tsc, T1, 
  Ts<-rlunif(1,100,10000000)#bound=[100-10000000]
  N1<-rlunif(1,100,100000)#bound=[100-100000]
  N2<-rlunif(1,100,100000)#bound=[100-100000]
  M12<-runif(1,0.01,6)#bound=[0.01-6]
  M21<-runif(1,0.01,6)#bound=[0.01-6]
  Tsc<-rlunif(1,10,1000000)#bound=[0-100]
  Te<-rlunif(1,10,10000000)#)#bound=[10,10000000]
  ex<-runif(1,0.0001,10000)#)#bound=[0.0001,10000]
  #print( Ts,  N1, N2,  M12, M21, Tsc)
  m_demo=matrix(c(Ts,N1,N2,M12,M21,Tsc),ncol=6)
  m_demo=as.data.frame(m_demo)
  locus<-cbind(m_locus,m_demo)
    path <- "/home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/fastSimBac_linux/Priors_SCex_10000/locus"
    write.table(locus,file= paste(path,i, sep="-"),col.names=FALSE,row.names =FALSE)
}
```

## Distribution des Priors 



```{r pressure, echo=F}
head(locus)
```

## Simuation des arbres selon les Priors
```{r}
setwd("/home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/fastSimBac_linux/Priors_SC")
```


```{bash}
#SC

########Param_demo (7) =   N1,  N2, Ts, Tsc,  T1, M12, M21 # -I 2 13 17 -m 1 2   M12 -m 2 1   M21  -en Te1 1  N’1 -en  Te2 2 N’2  -n  1  N1 -n  2 N2 -ej Ts 1 2
#L locus lengh
#t theta
#r rho
# λ length of recombining intervals
#N1 size pop1
#N2 size pop2
#Ts time scale of split
for i in /home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/fastSimBac_linux/Priors_SC/locus*
do
    while read line 
do 
    L=`echo $line | cut -d" " -f1`
    t=`echo $line | cut -d" " -f2`
    r=`echo $line | cut -d" " -f3`
    delta=`echo $line | cut -d" " -f4`
    TS=`echo $line | cut -d" " -f5`
    N1=`echo $line | cut -d" " -f6`
    N2=`echo $line | cut -d" " -f7`
    M12=`echo $line | cut -d" " -f8`
    M21=`echo $line | cut -d" " -f9`
    Tsc=`echo $line | cut -d" " -f10`
    #echo -ne "\t"$L"\t"$t"\t"$r"\t"$delta"\t"$N1"\t"$N2"\t"$TS"\t"$M12"\t"$M21"\n" >> logIM.txt

echo ./fastSimBac 30 $L -T -t $t -r $r $delta -I 2 13 17 -ej $TS 1 2 -n 1 $N1 -n 2 $N2   -m  1 2  $M12  -m  2 1  $M21 -eM $Tsc  0   >>$i.SC
   ./fastSimBac 30 $L -T -t $t -r $r $delta -I 2 13 17  -ej $TS 1 2 -n 1 $N1 -n 2 $N2   -m  1 2  $M12  -m  2 1  $M21 -eM $Tsc  0   >>$i.SC  
done < $i
done

```

