---
title: "Bpfile_2pops_13paucamulti"
author: "karine Durand"
date: "7 mars 2019"

output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## production des priors SI

``

####mon_script
```{r}
library(stats)
library("KScorrect", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.3")
######partie locus 
#variables locus
#-L=taille du gene
#-t=theta
#-r=rho
#-delta=taille du track recombinant
#boucle de 1000000 iterations(1000000 tirage demographique)
demo<-NULL
locus<-NULL
tbs<-NULL
#####TIRER un prior locus dans une distribution uniforme de bornes 
#L<-scan("/home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/1368oRTHOLOGUES_summarystats/lenght")#bound_taille du gene[100-2500]
L<-scan("/home/kadurand/partage_windows/Xylella/analyses_genomiques/ABC/obs/1368oRTHOLOGUES_summarystats/1368lenght")#bound_taille du gene[100-2500]
#t<-runif(997, 0.081407 )#8.1407E-07 pour N0=100000
 #r<-runif(997,0.081407)#bound_rho=[0-0.0003]bornes vrai pour 13pauca_multiplex augmenter la borne sup à 0.001]
t<-c(rep(0.00162814,1368))
r<-c(rep(0.00162814,1368))
nspA<-c(rep(13, 1368))
nspB<-c(rep(17, 1368))
delta<-round(runif(1368,10, 1000))#bound=[10-1000]
#print(L,t,r,delta)
rbind(L,delta, nspA,nspB,t*L,r*L)->bpfile



path <- "/home//kadurand/partage_windows/Xylella/analyses_genomiques/ABC/priorgen_13paucamulti/" 
write.table(bpfile,file= "/home//kadurand/partage_windows/Xylella/analyses_genomiques/ABC/fastSimBac_linux/fastsimbac_surgenes_13paucaCVC_multi//bpfile_1368PAUCAMULTI",col.names=FALSE,row.names =FALSE)

```

